#!/usr/bin/env node
// Build static HTML report from findings JSON; run secret scan; auto-open
// Usage: node build-report.js <findings-json> <project-dir> [--open]

const fs = require('fs');
const path = require('path');
const { execSync, spawnSync } = require('child_process');

const findingsPath = process.argv[2];
const projectDir = process.argv[3] || process.cwd();
const shouldOpen = process.argv.includes('--open');

if (!findingsPath || !fs.existsSync(findingsPath)) { console.error('findings json required'); process.exit(1); }
const data = JSON.parse(fs.readFileSync(findingsPath, 'utf8'));

const ts = new Date().toISOString().replace(/[:]/g, '-').slice(0, 19);
const reportDir = path.join(projectDir, '.qa', 'reports', ts);
fs.mkdirSync(reportDir, { recursive: true });

const findings = data.findings || [];
const sevCounts = findings.reduce((a, f) => { a[`sev${f.severity}`] = (a[`sev${f.severity}`] || 0) + 1; return a; }, {});
const sevColor = { 1: '#c0392b', 2: '#e67e22', 3: '#f1c40f', 4: '#7f8c8d' };
const sevLabel = { 1: 'Sev 1 (block)', 2: 'Sev 2 (sprint)', 3: 'Sev 3 (backlog)', 4: 'Sev 4 (info)' };

let coverageHtml = `
  <ul>
    <li>✓ Functional smoke (page loads, console errors, link integrity)</li>
    <li>✓ Visual regression (deterministic, golden-anchored): <em>not yet implemented in v1.3 runtime; coming v1.4</em></li>
    <li>✓ Accessibility (axe-core, WCAG 2.2 AA)</li>
    <li>✓ Performance (Lighthouse): <em>not in smoke; run /qa:full</em></li>
    <li>✗ Data correctness: <em>${data.data_adapter ? data.data_adapter : 'no adapter configured'}</em></li>
  </ul>
`;

let html = `<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><title>qa-pro report — ${data.project}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, sans-serif; max-width: 980px; margin: 32px auto; padding: 0 24px; color: #2c3e50; }
  h1 { margin: 0 0 4px 0; font-size: 24px; }
  .meta { color: #7f8c8d; font-size: 13px; margin-bottom: 24px; }
  .summary { display: flex; gap: 12px; margin: 24px 0; }
  .pill { padding: 8px 12px; border-radius: 6px; color: white; font-weight: 600; font-size: 13px; }
  .coverage { background: #ecf0f1; padding: 16px; border-radius: 6px; margin-bottom: 24px; }
  .coverage ul { margin: 8px 0 0 0; padding-left: 20px; }
  .coverage li { margin: 4px 0; font-size: 14px; }
  .finding { border-left: 4px solid #bdc3c7; padding: 12px 16px; margin: 12px 0; background: #f8f9fa; border-radius: 0 4px 4px 0; }
  .finding.s1 { border-left-color: #c0392b; }
  .finding.s2 { border-left-color: #e67e22; }
  .finding.s3 { border-left-color: #f1c40f; }
  .finding.s4 { border-left-color: #7f8c8d; }
  .finding-h { font-weight: 600; margin-bottom: 4px; }
  .finding-meta { font-size: 12px; color: #7f8c8d; margin-bottom: 8px; }
  .finding-detail { font-size: 13px; color: #34495e; }
  .finding-detail pre { background: white; padding: 8px; border-radius: 4px; overflow-x: auto; font-size: 12px; }
  .empty { text-align: center; padding: 48px; color: #7f8c8d; }
  .banner { background: #e74c3c; color: white; padding: 12px 16px; border-radius: 4px; margin-bottom: 16px; font-weight: 600; }
  .banner-warn { background: #f39c12; }
</style></head><body>
<h1>qa-pro report</h1>
<div class="meta">${data.project || 'unknown'} · ${data.test_url || ''} · ${data.startedAt} → ${data.finishedAt}</div>

<div class="coverage"><strong>Coverage</strong>${coverageHtml}</div>

<div class="summary">
${[1, 2, 3, 4].map(s => `<div class="pill" style="background: ${sevColor[s]}">${sevLabel[s]}: ${sevCounts['sev' + s] || 0}</div>`).join('')}
</div>

${findings.length === 0 ? '<div class="empty">No findings. Suite is clean.</div>' : ''}

${findings.map(f => `
<div class="finding s${f.severity}">
  <div class="finding-h">[Sev ${f.severity}] [${f.layer}] ${escapeHtml(f.finding)}</div>
  <div class="finding-meta">page: ${escapeHtml(f.page || '')}${f.url ? ` · <a href="${escapeHtml(f.url)}">${escapeHtml(f.url)}</a>` : ''}</div>
  ${f.detail ? `<div class="finding-detail"><pre>${escapeHtml(JSON.stringify(f.detail, null, 2))}</pre></div>` : ''}
</div>
`).join('')}

<div class="meta" style="margin-top: 48px; padding-top: 16px; border-top: 1px solid #ecf0f1;">
  Generated by qa-pro v1.3 · ${new Date().toISOString()}
</div>

</body></html>`;

function escapeHtml(s) {
  return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

const indexPath = path.join(reportDir, 'index.html');
fs.writeFileSync(indexPath, html);
fs.writeFileSync(path.join(reportDir, 'findings.json'), JSON.stringify(data, null, 2));

// Run secret scan + redaction
const scan = spawnSync('node', [path.join(__dirname, 'secret-scan.js'), indexPath, '--redact-in-place'], { encoding: 'utf8' });
let scanResult = {};
try { scanResult = JSON.parse(scan.stdout || '{}'); } catch {}

console.log(JSON.stringify({ report: indexPath, secret_scan: scanResult, sevCounts, total_findings: findings.length }, null, 2));

if (shouldOpen) {
  const isWin = process.platform === 'win32';
  const isMac = process.platform === 'darwin';
  try {
    if (isWin) execSync(`start "" "${indexPath}"`, { shell: true });
    else if (isMac) execSync(`open "${indexPath}"`);
    else execSync(`xdg-open "${indexPath}"`);
  } catch (e) { console.error(`could not auto-open: ${e.message}`); }
}
